version: "3.8"

services:
  web-example:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./static:/www/static:ro
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
