DROP TABLE tickets IF EXISTS;

--Tickets
CREATE TABLE tickets (
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         receipt_number INTEGER,
                         purchase_date VARCHAR(10),
                         items_purchased VARCHAR(255),
                         quantity INTEGER,
                         price_per_item DECIMAL(10,2),
                         total_amount DECIMAL(10, 2),
                         payment_method VARCHAR(50),
                         store_location VARCHAR(100),
                         cashier_name VARCHAR(100),
                         card_number VARCHAR(16)
);

