version: '3.8'

services:
  app:
    build: .
    ports:
      - "11000:11000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: bach-et-buck
      MARIADB_DATABASE: customers
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
